name: CI

on: [push, pull_request]

jobs:
  test_x86:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install-dependencies
      run: | 
            sudo apt-get update
            sudo apt-get install libsdl2-dev
    - name: make
      run: make
    - name: make check
      run: make check

  coding_convention:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: coding convention
      run: |
            sudo apt-get update
            sudo apt install clang-format colordiff
            sh .ci/style_check.sh
      shell: bash

